Title: Github workflow check. Type: Fix Component: CI Detail:     - github workflow expect artifacts available out side docker.     To handle this we created and mounted folder inside docker.     - Added logic in test_ci.sh to copy build artifacts

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -3,7 +3,8 @@ commit_msg_file=$1
 commit_msg=$(cat "$commit_msg_file")
 
 regex_title="^Title: .+"
-regex_type="^Type: (CI|git|Test|Code|Docs|Req|Example)$"
+regex_type="^Type: (Feature|Fix)$"
+regex_comp="^Component: (CI|git|Test|Code|Docs|Req|Example)$"
 regex_detail="^Detail:"
 
 # Check Title
@@ -12,9 +13,15 @@ echo "$commit_msg" | grep -qE "$regex_title" || {
   exit 1
 }
 
-# Check Type
+# Check Component
 echo "$commit_msg" | grep -qE "$regex_type" || {
-  echo "❌ Commit message missing or invalid Type (must be one of CI|Test|Code|Docs|Req|Example)" >&2
+  echo "❌ Commit message missing or invalid Type (must be one of Feature|Fix)" >&2
+  exit 1
+}
+
+# Check Component
+echo "$commit_msg" | grep -qE "$regex_comp" || {
+  echo "❌ Commit message missing or invalid Component (must be one of CI|Test|Code|Docs|Req|Example)" >&2
   exit 1
 }
 
